---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
    mintmaker.appstudio.redhat.com/disabled: 'true'
    git-provider: github
    git-provider-url: https://github.com
  name: feast-group
  namespace: open-data-hub-tenant
spec:
  application: group-testing
  componentName: feast-group
  containerImage: quay.io/redhat-user-workloads/open-data-hub-tenant/feast-group
  source:
    git:
      dockerfileUrl: Dockerfile
      url: https://github.com/opendatahub-io/feast
      revision: "stable"
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
    mintmaker.appstudio.redhat.com/disabled: 'true'
    git-provider: github
    git-provider-url: https://github.com
  name: kserve-group
  namespace: open-data-hub-tenant
spec:
  application: group-testing
  componentName: kserve-group
  containerImage: quay.io/redhat-user-workloads/open-data-hub-tenant/kserve-group
  source:
    git:
      dockerfileUrl: Dockerfile
      url: https://github.com/opendatahub-io/kserve
      revision: "master"
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
    mintmaker.appstudio.redhat.com/disabled: 'true'
    git-provider: github
    git-provider-url: https://github.com
  name: kubeflow-group
  namespace: open-data-hub-tenant
spec:
  application: group-testing
  componentName: kubeflow-group
  containerImage: quay.io/redhat-user-workloads/open-data-hub-tenant/kubeflow-group
  source:
    git:
      context: components
      dockerfileUrl: notebook-controller/Dockerfile
      revision: stable
      url: https://github.com/opendatahub-io/kubeflow.git
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: odh-model-controller-ci-its-manual
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-builds
  contexts:
    - description: execute the integration test when component odh-operator updates
      name: component_odh-model-controller-ci
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/odh-model-controller/pr-test-pipelinerun.yaml
    resolver: git
    resourceKind: pipelinerun

---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: models-as-a-service-ci-its-manual
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-builds
  contexts:
    - description: execute the integration test when component maas-api updates
      name: component_odh-maas-api-ci
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/models-as-a-service/pr-test-pipelinerun.yaml
    resolver: git
    resourceKind: pipelinerun
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: models-as-a-service-controller-ci-its-manual
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-builds
  contexts:
    - description: execute the integration test when component maas-controller updates
      name: component_odh-maas-controller-ci
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/models-as-a-service/pr-test-pipelinerun.yaml
    resolver: git
    resourceKind: pipelinerun
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: odh-operator-ci-e2e-its-manual
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-builds
  contexts:
    - description: execute the integration test when component odh-operator updates
      name: component_odh-operator-ci
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/opendatahub-operator/pr-test-pipelinerun.yaml
    resolver: git
    resourceKind: pipelinerun
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: trainer-ci-its-manual
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-builds
  contexts:
    - description: execute the integration test when component trainer-ci updates
      name: component_trainer-ci
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/trainer/pr-testing-pipeline.yaml
    resolver: git
    resourceKind: pipelinerun
